### ISSUE TITLE
_config.yml

### ISSUE THREAD

**Issue by danmichaelo** [LeidenUniversityLibrary/Library-Search-Plugin-Public#3]
Thanks for the nice devday presentation today! The plugin was indeed easy to get started with :) Just one issue I encountered when loading the package into Chrome ("Load unpacked"):

<img width="523" alt="screen shot 2018-08-23 at 18 15 55" src="https://user-images.githubusercontent.com/434495/44538102-b6972f00-a700-11e8-9e0c-f28a1742bb22.png">

Removing the file resolved the problem. Is it used for anything?

**Comment by Dioscorides** [comment]
Nope, not used for anything in the plugin, but by github to create the page at https://leidenuniversitylibrary.github.io/Library-Search-Plugin-Public/ ... i'll make it disappear asap! Thank you for letting me know :)

**Comment by danmichaelo** [comment]
Aha, I wasn't aware you could create gh pages directly from the readme! That's quite cool, hope you find a solution :)

**Comment by Dioscorides** [comment]
Should be gone now... (added a .gitignore which also has to be deleted when downloaded, but should be prettier...)
