### ISSUE TITLE
Duplicate IDs error

### ISSUE THREAD

**Issue by Dioscorides** [LeidenUniversityLibrary/Library-Search-Plugin-Public#6]
When opening the plugin's popup.html, the console outputs an error mentioning duplicate IDs. This is because options.js repeatedly calls the "context menu" options, every time the popup is opened by the user.

1. Move the context menu options from options.js to a new file called background.js.
2. in manifest.json, call background.js instead of popup.html in the "background" section of the json.

**Comment by bencomp** [comment]
That looks sensible – the background scripts are run when the addon is loaded, so that is where you want to initialise context menus.
